<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <Compile Remove="Pages\**" />
    <Content Remove="Pages\**" />
    <EmbeddedResource Remove="Pages\**" />
    <None Remove="Pages\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\img\citas-image.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MedCitas.Core\MedCitas.Core.csproj" />
    <ProjectReference Include="..\MedCitas.Infrastructure\MedCitas.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c21fa7d0-fe89-486b-a1c2-5f4086da538f</UserSecretsId>
  </PropertyGroup>

</Project>
